NOTE: Redirects are currently not supported in Windows or MacOs.
/opt/homebrew/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py:163: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
WARNING:torch.distributed.run:--use_env is deprecated and will be removed in future releases.
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : ./tools/test.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:28596
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /var/folders/bl/c09z1sm91mxfb8z7mn7v4rhh0000gq/T/torchelastic_e9omo8ks/none_0bhtlrb4
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
/opt/homebrew/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:52: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=28596
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /var/folders/bl/c09z1sm91mxfb8z7mn7v4rhh0000gq/T/torchelastic_e9omo8ks/none_0bhtlrb4/attempt_0/0/error.json
Traceback (most recent call last):
  File "./tools/test.py", line 16, in <module>
    from projects.mmdet3d_plugin.datasets.build_dataset import build_dataset
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/__init__.py", line 5, in <module>
    from .datasets.pipelines import (
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/datasets/__init__.py", line 1, in <module>
    from .nuscenes_e2e_dataset import NuScenesE2EDataset
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 13, in <module>
    from .nuscenes_dataset import NuScenesDataset
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py", line 16, in <module>
    from projects.mmdet3d_plugin.datasets.custom_3d import Custom3DDataset
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/datasets/custom_3d.py", line 12, in <module>
    from projects.mmdet3d_plugin.datasets.util import extract_result_dict, get_loading_pipeline
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/datasets/util.py", line 5, in <module>
    from projects.mmdet3d_plugin.datasets.pipelines.loading import (LoadAnnotations3D,
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/datasets/pipelines/__init__.py", line 6, in <module>
    from .occflow_label import GenerateOccFlowLabels
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/datasets/pipelines/occflow_label.py", line 5, in <module>
    from projects.mmdet3d_plugin.uniad.dense_heads.occ_head_plugin import calculate_birds_eye_view_parameters
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/uniad/__init__.py", line 3, in <module>
    from .detectors import *
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/uniad/detectors/__init__.py", line 1, in <module>
    from .uniad_e2e import UniAD
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/uniad/detectors/uniad_e2e.py", line 13, in <module>
    from .uniad_track import UniADTrack
  File "/Users/liangming.xu/code/UniAD/projects/mmdet3d_plugin/uniad/detectors/uniad_track.py", line 11, in <module>
    from mmdet3d.core import bbox3d2result
ModuleNotFoundError: No module named 'mmdet3d'
